// ignore_for_file: constant_identifier_names

@Deprecated("Use 'package:dsp_base/convenience_imports.dart' instead")
library;

class RconfComm {
  // Analytics Configuration Keys
  static const String COMM_IS_ENABLE_ANALYTICS = "COMM_IS_ENABLE_ANALYTICS";
  static const String COMM_IS_ENABLE_ADS_ANALYTICS = "COMM_IS_ENABLE_ADS_ANALYTICS";
  static const String COMM_IS_ENABLE_ADS_BANNER_ANALYTICS = "COMM_IS_ENABLE_ADS_BANNER_ANALYTICS";
  static const String COMM_IS_ENABLE_ADS_VIDEO_ANALYTICS = "COMM_IS_ENABLE_ADS_VIDEO_ANALYTICS";
  static const String COMM_IS_ENABLE_ADS_NATIVE_ANALYTICS = "COMM_IS_ENABLE_ADS_NATIVE_ANALYTICS";
  static const String COMM_IS_ENABLE_ADS_INTER_ANALYTICS = "COMM_IS_ENABLE_ADS_INTER_ANALYTICS";
  static const String COMM_IS_ENABLE_ADS_OPEN_APP_ANALYTICS = "COMM_IS_ENABLE_ADS_OPEN_APP_ANALYTICS";

  static const String COMM_IS_ENABLE_IAP_ANALYTICS = "COMM_IS_ENABLE_IAP_ANALYTICS";
  static const String COMM_IS_ENABLE_OPEN_APP_ANALYTICS = "COMM_IS_ENABLE_OPEN_APP_ANALYTICS";
  static const String COMM_IS_ENABLE_CLICK_BUTTON_ANALYTICS = "COMM_IS_ENABLE_CLICK_BUTTON_ANALYTICS";
  static const String COMM_IS_ENABLE_PAID_AD_IMPRESSION_ANALYTICS = "COMM_IS_ENABLE_PAID_AD_IMPRESSION_ANALYTICS";
  static const String COMM_IS_ENABLE_SCREEN_VIEW_ANALYTICS = "COMM_IS_ENABLE_SCREEN_VIEW_ANALYTICS";
  static const String COMM_IS_ENABLE_RATE_ME_ANALYTICS = "COMM_IS_ENABLE_RATE_ME_ANALYTICS";
  static const String COMM_IS_ENABLE_USER_PROPERTIES = "COMM_IS_ENABLE_USER_PROPERTIES";
  static const String COMM_DELAY_INTER_ADS = "COMM_DELAY_INTER_ADS";
  static const String COMM_DELAY_INTER_ADS_BYPASS_ALLOWED = "COMM_DELAY_INTER_ADS_BYPASS_ALLOWED";
  static const String COMM_DELAY_INTER_ADS_BY_SCREEN_COUNT = "COMM_DELAY_INTER_ADS_BY_SCREEN_COUNT";

  // Ad Configuration Keys
  static const String COMM_ENABLE_AD_IMMERSIVE_MODE = "COMM_ENABLE_AD_IMMERSIVE_MODE";
  static const String COMM_ENABLE_BANNER_ADS = "COMM_ENABLE_BANNER_ADS";
  static const String COMM_ENABLE_NATIVE_ADS = "COMM_ENABLE_NATIVE_ADS";
  static const String COMM_ENABLE_INTER_ACTION_ADS = "COMM_ENABLE_INTER_ACTION_ADS";
  static const String COMM_ENABLE_INTER_OPEN_ADS = "COMM_ENABLE_INTER_OPEN_ADS";
  static const String COMM_ENABLE_OPEN_ADS_OPEN = "COMM_ENABLE_OPEN_ADS_OPEN";
  static const String COMM_ENABLE_OPEN_ADS_RESUME = "COMM_ENABLE_OPEN_ADS_RESUME";

  // Rate Me Configuration Keys
  static const String COMM_RATE_ME_4STAR_PLUS = "COMM_RATE_ME_4STAR_PLUS";
  static const String COMM_RATE_ME_BELOW_3STAR_PLUS = "COMM_RATE_ME_BELOW_3STAR_PLUS";
  static const String COMM_RATE_ME_SHOW_CLOSE_BUTTON = "COMM_RATE_ME_SHOW_CLOSE_BUTTON";

  // In-App Update Configuration Keys
  static const String COMM_IN_APP_UPDATE_ENABLED = "COMM_IN_APP_UPDATE_ENABLED";
  static const String COMM_IN_APP_UPDATE_MINIMUM_APP_VERSION = "COMM_IN_APP_UPDATE_MINIMUM_APP_VERSION";
  static const String COMM_IN_APP_UPDATE_NEW_VERSION_STALENESS_DAYS_RE_PROMPT =
      "COMM_IN_APP_UPDATE_NEW_VERSION_STALENESS_DAYS_RE_PROMPT";
  static const String COMM_IN_APP_UPDATE_NEW_VERSION_STALENESS_DAYS_THRESHOLD =
      "COMM_IN_APP_UPDATE_NEW_VERSION_STALENESS_DAYS_THRESHOLD";
}
